api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('halls/delete/', views.delete_hall, name='hall_delete'),
    path('halls/update/', views.update_hall, name='hall_update'),
    path('halls/video/delete/', views.delete_video, name='video_delete'),
]

halls/urls.py
from django.urls import path

from halls import views

app_name = 'hall'

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),

    path('halloffame/create/', views.HallCreateView.as_view(), name='hall-create'),
    path('halloffame/<int:pk>', views.HallDetailView.as_view(), name='hall-detail'),
    path('halloffame/<int:pk>/update/', views.HallUpdateView.as_view(), name='hall-update'),
    path('halloffame/<int:pk>/delete/', views.HallDeleteView.as_view(), name='hall-delete'),

    path('halloffame/<int:pk>/add-video/', views.add_video, name='hall-add-video'),
    path('video/search/', views.video_search, name='video_search'),
    path('video/<int:pk>/delete/', views.VideoDeleteView.as_view(), name='video-delete'),
]

hofvideo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from halls.views import HallMainPage

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HallMainPage.as_view(), name='home'),

    path('', include('halls.urls')),
    path('auth/', include('users.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserSignUpView

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login',),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
]

halls/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Hall(models.Model):

    title = models.CharField('Hall Title', max_length=255)
    user = models.ForeignKey(
        get_user_model(),
        verbose_name='User',
        on_delete=models.CASCADE,
        related_name='halls',
    )

    class Meta:
        verbose_name = 'Hall'
        verbose_name_plural = 'Halls'

    def __str__(self):
        return self.title


class Video(models.Model):

    title = models.CharField('Video Title', max_length=255)
    url = models.URLField('Video URL')
    youtube_id = models.CharField('YouTube ID', max_length=255)
    hall = models.ForeignKey(
        'halls.Hall',
        verbose_name='Hall',
        on_delete=models.CASCADE,
        related_name='videos',
    )

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

    def __str__(self):
        return self.title

halls/forms.py
from django import forms
from django.forms import modelformset_factory

from halls.models import Hall, Video
from halls.youtube import get_yotube_title, parse_youtube_url


class VideoForm(forms.ModelForm):
    """Form to add video for a hall."""

    class Meta:
        model = Video
        fields = ('url', )
        labels = {'url': 'YouTube URL'}
        widgets = {
            'url': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean(self):
        url = self.cleaned_data['url']
        if parse_youtube_url(url) is None:
            raise forms.ValidationError('Needs to be the valid YouTube video URL')

        video_id = parse_youtube_url(url)
        if get_yotube_title(video_id) is None:
            raise forms.ValidationError('Needs to be the valid YouTube video URL')


class SearchForm(forms.Form):
    """Search video in the TouTube form."""

    search = forms.CharField(label='Search for Videos', max_length=255)


class HallForm(forms.ModelForm):
    """Form to create Hall."""

    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control my-3', 'required': True}),
    )

    class Meta:
        model = Hall
        fields = ('title', )


HallFormset = modelformset_factory(
    Hall,
    form=HallForm,
    extra=1,
)

halls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from halls.forms import HallFormset, SearchForm, VideoForm
from halls.models import Hall, Video
from halls.youtube import (get_yotube_title, parse_youtube_url,
                           search_videos_in_youtube)


@login_required
def add_video(request, pk):
    """Add video to the exact hall."""
    search_form = SearchForm()
    hall = get_object_or_404(Hall, pk=pk)
    if not hall.user == request.user:
        raise Http404

    if request.method == 'POST':
        form = VideoForm(request.POST)

        if form.is_valid():
            video = Video()
            video.url = form.cleaned_data.get('url')
            video_id = parse_youtube_url(video.url)[0]
            if video_id:
                video.hall = hall
                video.youtube_id = video_id
                video.title = get_yotube_title(video_id)
                video.save()
                return redirect('hall:hall-detail', pk=pk)
    else:
        form = VideoForm()

    return render(
        request,
        'halls/add_video.html',
        {'search_form': search_form, 'hall': hall, 'form': form},
    )


@login_required
def video_search(request):
    """Return finding videos form searcg form."""
    form = SearchForm(request.GET)

    if form.is_valid():
        search_text = form.cleaned_data.get('search')
        videos = search_videos_in_youtube(search_text)

        return JsonResponse(videos)

    return JsonResponse({'error': 'Not able to validate form.'})


class VideoDeleteView(LoginRequiredMixin, DeleteView):
    """Delete video."""

    model = Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('hall:dashboard')

    def get_object(self):
        video = super().get_object()
        if video.hall.user != self.request.user:
            raise Http404
        return video


class HallMainPage(ListView):
    """View to represent main page."""

    template_name = 'halls/index.html'
    queryset = Hall.objects.all().order_by('-id')[:5]
    context_object_name = 'halls'


class DashboardView(LoginRequiredMixin, ListView):
    """View for an user dashboard."""

    template_name = 'halls/dashboard.html'
    model = Hall
    context_object_name = 'halls'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user).prefetch_related('videos')


class HallCreateView(LoginRequiredMixin, CreateView):
    """Create Hall for an authenticated user."""

    model = Hall
    fields = ('title', )
    template_name = 'halls/create_hall.html'
    success_url = reverse_lazy('hall:dashboard')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = HallFormset(queryset=Hall.objects.none())
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        formset = HallFormset(request.POST, request.FILES)

        if formset.is_valid():
            for form in formset:
                form.instance.user = self.request.user
            formset.save()
            return redirect('hall:dashboard')
        else:
            return self.form_invalid(formset)

    def form_invalid(self, formset):
        return self.render_to_response(self.get_context_data(formset=formset))


class HallDetailView(DetailView):
    """Hall detail page."""

    model = Hall
    template_name = 'halls/detail_hall.html'


class HallUpdateView(LoginRequiredMixin, UpdateView):
    """Hall update view for own user."""

    model = Hall
    fields = ('title', )
    template_name = 'halls/update_hall.html'
    success_url = reverse_lazy('hall:dashboard')

    def get_object(self):
        hall = super().get_object()
        if hall.user != self.request.user:
            raise Http404
        return hall


class HallDeleteView(LoginRequiredMixin, DeleteView):
    """Delete hall from own user."""

    model = Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('hall:dashboard')

    def get_object(self):
        hall = super().get_object()
        if hall.user != self.request.user:
            raise Http404
        return hall

templates/halls/add_video.html
{% extends 'halls/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Add video{% endblock %}

{% block content %}

<h2 class="my-4">Add video into {{ hall }}</h2>

<form method="post" class="mt-4" id="submit_video">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Add Video</button>
  <a class="btn btn-outline-secondary" href="{% url 'hall:hall-detail' request.resolver_match.kwargs.pk %}" role="button">Cancel</a>
</form>

<h2 class="mt-4">OR</h2>
<form method="post" class="mt-4" action="{% url 'hall:video_search' %}">
  {% csrf_token %}
  {% for field in search_form %}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }}
    {% render_field field class="form-control"%}
  </div>
  {% endfor %}
</form>

<div id="search_results"></div>

{% endblock %}

{% block js_script %}
  <script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

templates/halls/base.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{% block title %}{% endblock %}</title>

  <script type="text/javascript" nonce="aab4c1fce8324357bda9bc8b253"
    src="//local.adguard.org?ts=1593180398924&amp;type=content-script&amp;dmn=att-a.udemycdn.com&amp;css=1&amp;js=1&amp;gcss=1&amp;rel=1&amp;rji=1&amp;stealth=1&amp;uag=&amp;trref=aHR0cHM6Ly9hdHQtYS51ZGVteWNkbi5jb20v">
  </script>
  <script type="text/javascript" nonce="aab4c1fce8324357bda9bc8b253"
    src="//local.adguard.org?ts=1593180398924&amp;name=Web%20of%20Trust&amp;name=AdGuard%20Popup%20Blocker&amp;name=AdGuard%20Extra&amp;type=user-script">
  </script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link href="{% static 'css/original.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'img/original.ico' %}" />
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Hall of Fame Vidz</a>
    </h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'hall:dashboard' %}">Dashboard</a>
        <a class="p-2 text-dark" href="{% url 'user:logout' %}">Log Out</a>
      {% else %}
        <a class="p-2 text-dark" href="{% url 'user:login' %}">Log In</a>
      {% endif %}
    </nav>

    {% if not user.is_authenticated %}
      <a class="btn btn-outline-primary {% if request.resolver_match.url_name == 'signup' %}disabled{% endif %}"
        href="{% url 'user:signup' %}">Sign up</a>
    {% endif %}
  </div>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  {% block js_script %}{% endblock %}

</body>

</html>

templates/halls/create_hall.html
{% extends 'halls/base.html' %}

{% load widget_tweaks %}

{% block title %}Create Hall{% endblock %}

{% block content %}
<h2 class="my-4">Create Hall Of Fame</h2>

<form method="post" class="mt-4">
  {% csrf_token %}

  {{ formset.management_form }}
  <div id="form_set">
    {% for form in formset.forms %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
      {{ form }}

    {% endfor %}

  </div>

  <input type="button" value="Add More" id="add_more" class="btn btn-primary">
  <button type="submit" class="btn btn-primary">Create Hall</button>

</form>

<div id="empty_form" style="display:none">
  {{ formset.empty_form }}
</div>

{% endblock %}

{% block js_script %}
<script>
  $('#add_more').click(function () {
    var form_idx = $('#id_form-TOTAL_FORMS').val();
    $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
    $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
  });
</script>
{% endblock %}

templates/halls/dashboard.html
{% extends 'halls/base.html' %}

{% block title %}User Dashboard{% endblock %}

{% block content %}
<div class="text-center">
  <h1 class="my-4">Hall Of Fames</h1>
  <a href="{% url 'hall:hall-create' %}" class="btn btn-success mb-4">Creare new Hall of Fame</a>
</div>

  {% for hall in halls %}

  <div class="hall">
    <h2 class="my-3"><a href="{% url 'hall:hall-detail' hall.pk %}">{{ hall }}</a></h2>

      <input type="button" value="Delete" class="btn btn-danger hall-delete" data-hall="{{hall.id}}">
      <a href="{% url 'hall:hall-detail' hall.pk %}" class="btn btn-primary">Edit Hall</a>
      <a href="{% url 'hall:hall-add-video' hall.pk %}" class="btn btn-primary">Add Video To Hall</a>


    <div class="row">
      {% for video in hall.videos.all|slice:":3" %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endfor %}

{% endblock %}

{% block js_script %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
    document.addEventListener('click', event => {
      let element = event.target;

      if (element.value == 'Delete') {
        element.parentElement.style.animationPlayState = 'running';
        element.parentElement.addEventListener('animationend', () => {
          element.parentElement.remove();
          delete_hall(element.dataset.hall);
        });
      }
    })
  })

  let delete_hall = (hall_id) => {
    fetch(`/api/halls/delete/`, {
      method: 'DELETE',
      body: JSON.stringify({'hall_id': hall_id})
    })
  }
</script>
{% endblock %}

templates/halls/delete_hall.html
{% extends 'halls/base.html' %}

{% block title %}Deelete {{ object }}{% endblock %}

{% block content %}
<h2 class="my-4">Delete {{ hall }} ?</h2>

<form method="post" class="mt-4">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-danger mt-3">Delete</button>
</form>

<a href="{% url 'hall:hall-detail' hall.pk %}" class="btn btn-success my-3">Back to {{ hall }}</a>

{% endblock %}

templates/halls/delete_video.html
{% extends 'halls/base.html' %}

{% block title %}Deelete {{ object }}{% endblock %}

{% block content %}
<h2 class="my-4">Delete this video ?</h2>

<form method="post" class="mt-4">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-danger mt-3">Delete</button>
</form>

<div class="row">
  <div class="col-md-4 mt-3">
    <div class="card mb-4 shadow-sm">
      <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ object.youtube_id }}"
        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>
      <div class="card-body">
        <p class="card-text">{{ object.title }}</p>
      </div>
    </div>
  </div>
</div>

<a href="{% url 'hall-detail' object.hall.pk %}" class="btn btn-success my-3">Back to {{ object.hall }}</a>

{% endblock %}

templates/halls/detail_hall.html
{% extends 'halls/base.html' %}

{% block title %}Hall {{ hall }}{% endblock %}

{% block content %}
<h1 class="my-4 post-title">{{ hall }}</h1>

<textarea id="post-title-text" class="form-control mt-5 mb-3" cols="30" rows="2"
  style="display: none;">{{ hall.title }}</textarea>
 <input type="button" value="Update" class="btn btn-success w-25 update" style="display: none;">

{% if user.id == hall.user.id %}
<div class="my-3 hall-buttons">
  <input type="button" value="Delete" class="btn btn-danger hall-delete" data-hall="{{ hall.id }}">
  <input type="button" value="Edit" class="btn btn-primary hall-edit" data-hall="{{ hall.id }}">
  <a href="{% url 'hall:hall-add-video' hall.pk %}" class="btn btn-primary add">Add Video To Hall</a>
  <a href="{% url 'hall:dashboard' %}" class="btn btn-outline-secondary cancel">Cancel</a>
</div>
{% endif %}

<div class="row">
  {% for video in hall.videos.all %}
  <div class="col-md-4 mt-3 video">
    <div class="card mb-4 shadow-sm">
      <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <div class="card-body">
        <p class="card-text">{{ video.title }}</p>
        {% if user.id == hall.user.id %}
        <input type="button" value="Delete Video" class="btn btn-danger video-delete" data-video="{{ video.id }}">
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

{% block js_script %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
    document.addEventListener('click', event => {
      let element = event.target;

      if (element.value === 'Edit') {
        edit_hall(element.dataset.hall);
      }
      else if (element.value === 'Delete') {
        delete_hall(element.dataset.hall);
      }
      else if (element.value === 'Delete Video') {
        let video = element.parentElement.parentElement.parentElement

        video.style.animationPlayState = 'running';
        video.addEventListener('animationend', () => {
          video.remove();
          delete_video(element.dataset.video);
        })
      }
    })
  })

  let delete_video = (video_id) => {
    fetch('/api/halls/video/delete/', {
      method: 'DELETE',
      body: JSON.stringify({'video_id': video_id})
    })
  }

  let delete_hall = (hall_id) => {
    fetch(`/api/halls/delete/`, {
      method: 'DELETE',
      body: JSON.stringify({'hall_id': hall_id})
    })
    .then(response => {
      redirect: window.location.replace("{% url 'hall:dashboard' %}");
    })
  }

  let edit_hall = (hall_id) => {
    let textarea = document.querySelector('#post-title-text');
    let update_button = document.querySelector('.update')

    document.querySelector('.post-title').style.display = 'none';
    document.querySelector('.hall-buttons').style.display = 'none';
    textarea.style.display = 'block';
    update_button.style.display = 'block';

    update_button.addEventListener('click', () => {

      fetch('/api/halls/update/', {
          method: 'POST',
          body: JSON.stringify({
            'hall_id': hall_id,
            'text': textarea.value
          })
        })
        .then((response) => response.json())
        .then((result) => {
          if (result.status === 200) {
            textarea.style.display = 'none';
            document.querySelector('.post-title').textContent = textarea.value;
            document.querySelector('.post-title').style.display = 'block';
            document.querySelector('.hall-buttons').style.display = 'block';
            update_button.style.display = 'none';
          }
        })
    })
  }
</script>
{% endblock js_script %}

templates/halls/index.html
{% extends 'halls/base.html' %}

{% block title %}Hall Of Fame Videos{% endblock %}

{% block content %}
<section class="jumbotron text-center">
  <h1 class="jumbotron-heading">What's your personal Hall Of Fame for Videos?</h1>
  <p class="lead text-muted">You know they are. They're your goto videos. You have a top 10 list and it's time to share
    them with the world.
    Click the button below to get started.
  </p>
  <p><a href="{% url 'hall:hall-create' %}" class="btn btn-primary">Create Your Hall of Fame</a></p>
</section>

<h2 class="text-center">Recent Halls</h2>
{% for hall in halls %}

<h2><a href="{% url 'hall:hall-detail' hall.pk %}">{{ hall }}</a></h2>
<div class="row">
  {% for video in hall.videos.all|slice:":6" %}
  <div class="col-md-4 mt-3">
    <div class="card mb-4 shadow-sm">
      <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <div class="card-body">
        <p class="card-text">{{ video.title }}</p>
      </div>
    </div>
  </div>
  {% endfor %}

  </div>

{% empty %}
<div class="text-center my-4">Not available yet, be the first!</div>
{% endfor %}

{% endblock %}

templates/halls/update_hall.html
{% extends 'halls/base.html' %}

{% load widget_tweaks %}

{% block title %}Update {{ object }}{% endblock %}

{% block content %}
<h2 class="my-4">Update Hall Of Fame {{ hall }}</h2>

<form method="post" class="mt-4">
  {% csrf_token %}
  {% for field in form.visible_fields %}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }}
    {% render_field field class="form-control"%}
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary mt-3">Save {{ hall }}</button>
</form>

<a href="{% url 'hall:hall-delete' hall.pk %}" class="btn btn-danger my-3">Delete {{ hall }}</a>

{% endblock %}